---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: registry
  namespace: registry
spec:
  virtualhost:
    fqdn: HOST
  routes:
    - conditions:
      - prefix: /
      services:
        - name: registry
          port: 5000