#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:assert", "assert")

#@overlay/match by=overlay.subset({"kind":"Ingress", "metadata": {"name": "registry"}})
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kubernetes.io/ingress.class: #@ data.values.ingress.ingress_class
    #@overlay/match missing_ok=True
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
  #@overlay/match by=overlay.index(0)
  - host: #@ "registry.{}".format(data.values.domain)
  #@overlay/match missing_ok=True
  tls:
  - hosts:
    - #@ "registry.{}".format(data.values.domain)
    secretName: wildcard