#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ if/end data.values.create_namespace==True:
#@overlay/insert
---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.namespace

#@overlay/match by=overlay.subset({"metadata": {"namespace": "registry"}}), expects="0+"
---
metadata:
  namespace: #@ data.values.namespace
