#@data/values-schema
---
#! Namespace should be the same as cert-manager's namespace
namespace: registry
create_namespace: True

#! Which integrated services should be used (use True or False)
useContour: False
useCertManager: False
useStorage: True

domain: REPLACE_ME
registry:
  #! Empty to use default image.
  #! Use a different verion of distribution. See: https://github.com/distribution/distribution
  #! For ORAS related work use (ghcr.io/oras-project/registry:v1.0.0-rc.4) See: https://github.com/oras-project/distribution
  image: ""
  #! If storage is provided (e.g. 20Gi), then it will create a PVC of that size
  storage:
    size: 10Gi
    storage_class: default
  ingress:
    ingress_class: contour
  certmanager:
    secret:
      name: "" #! TODO: Make this secret copied into this namespace
      namespace: "" #! Specify namespace if TLS-Delegation is used
    clusterissuer: "" #! Specify cluster Issuer if you want cert-manager to create the cert for you
  auth:
    type: any #! any, htpasswd
    htpasswd:
      users:
        - name: USER
          password: PASSWORD
